image: clojure:temurin-21-tools-deps-bookworm-slim

stages:
  - test
  - build

variables:
  CLJ_CACHE: "$CI_PROJECT_DIR/.cpcache"

cache:
  key: "$CI_COMMIT_REF_SLUG"
  paths:
    - .cpcache/

test:
  stage: test
  script:
    - clojure -M:test

build:
  stage: build
  script:
    - clojure -T:build jar
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week
  only:
    - main
    - tags
